# Generated by Django 4.2.7 on 2024-01-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_enrollment_portal_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='portal_screenshot',
            field=models.FileField(upload_to='portal_screenshot/'),
        ),
    ]
